# Copyright 2023 Viasat Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

declare_args() {
  prism_enabled = true
  prism_hints_url = "https://prism-edge.viasat.workers.dev"
  prism_metrics_url = "https://apis.vega-preprod.viasat.io/v1/prism/ukms"
}
