// Copyright 2022 Viasat Inc. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "rebel/chrome/renderer/ntp/remote_ntp_extension.h"

#include <string>

#include "base/base64.h"
#include "base/strings/utf_string_conversions.h"
#include "base/system/sys_info.h"
#include "build/build_config.h"
#include "chrome/common/themes/autogenerated_theme_util.h"
#include "components/version_info/version_info.h"
#include "content/public/common/url_constants.h"
#include "content/public/common/url_utils.h"
#include "content/public/renderer/render_frame.h"
#include "gin/converter.h"
#include "gin/data_object_builder.h"
#include "gin/handle.h"
#include "gin/object_template_builder.h"
#include "gin/wrappable.h"
#include "third_party/blink/public/common/chrome_debug_urls.h"
#include "third_party/blink/public/web/blink.h"
#include "third_party/blink/public/web/web_document.h"
#include "third_party/blink/public/web/web_local_frame.h"
#include "third_party/blink/public/web/web_script_source.h"
#include "ui/base/l10n/l10n_util.h"
#include "ui/gfx/color_utils.h"
#include "v8/include/v8.h"

#if !defined(OS_ANDROID)
#include "chrome/browser/new_tab_page/chrome_colors/generated_colors_info.h"
#endif

#include "rebel/chrome/common/ntp/remote_ntp_types.h"
#include "rebel/chrome/renderer/ntp/remote_ntp.h"

namespace rebel {

namespace {

constexpr const char kDispatchNtpTilesChangedScript[] =
    "if (window.rebel &&"
    "    window.rebel.onNtpTilesChanged &&"
    "    (typeof window.rebel.onNtpTilesChanged === 'function')) {"
    "  window.rebel.onNtpTilesChanged();"
    "  true;"
    "}";

constexpr const char kDispatchAutocompleteResultChanged[] =
    "if (window.rebel &&"
    "    window.rebel.search &&"
    "    window.rebel.search.onAutocompleteResultChanged &&"
    "    (typeof window.rebel.search.onAutocompleteResultChanged"
    "        ===  'function')) {"
    "  window.rebel.search.onAutocompleteResultChanged();"
    "  true;"
    "}";

constexpr const char kDispatchBackgroundCollectionsChangedScript[] =
    "if (window.rebel &&"
    "    window.rebel.theme &&"
    "    window.rebel.theme.onBackgroundCollectionsChanged &&"
    "    (typeof window.rebel.theme.onBackgroundCollectionsChanged"
    "        ===  'function')) {"
    "  window.rebel.theme.onBackgroundCollectionsChanged();"
    "  true;"
    "}";

constexpr const char kDispatchBackgroundImagesChangedScript[] =
    "if (window.rebel &&"
    "    window.rebel.theme &&"
    "    window.rebel.theme.onBackgroundImagesChanged &&"
    "    (typeof window.rebel.theme.onBackgroundImagesChanged === "
    "        'function')) {"
    "  window.rebel.theme.onBackgroundImagesChanged();"
    "  true;"
    "}";

constexpr const char kDispatchLocalBackgroundImageSelectedScript[] =
    "if (window.rebel &&"
    "    window.rebel.theme &&"
    "    window.rebel.theme.onLocalBackgroundImageSelected &&"
    "    (typeof window.rebel.theme.onLocalBackgroundImageSelected"
    "        ===  'function')) {"
    "  window.rebel.theme.onLocalBackgroundImageSelected();"
    "  true;"
    "}";

constexpr const char kDispatchThemeChangedScript[] =
    "if (window.rebel &&"
    "    window.rebel.theme &&"
    "    window.rebel.theme.onThemeChanged &&"
    "    (typeof window.rebel.theme.onThemeChanged === 'function')) {"
    "  window.rebel.theme.onThemeChanged();"
    "  true;"
    "}";

void Dispatch(blink::WebLocalFrame* frame, const blink::WebString& script) {
  if (frame) {
    frame->ExecuteScript(blink::WebScriptSource(script));
  }
}

// Returns an array with the RGBA color components.
v8::Local<v8::Value> SkColorToArray(v8::Isolate* isolate,
                                    const SkColor& color) {
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Array> color_array = v8::Array::New(isolate, 4);

  color_array
      ->CreateDataProperty(context, 0,
                           v8::Int32::New(isolate, SkColorGetR(color)))
      .Check();
  color_array
      ->CreateDataProperty(context, 1,
                           v8::Int32::New(isolate, SkColorGetG(color)))
      .Check();
  color_array
      ->CreateDataProperty(context, 2,
                           v8::Int32::New(isolate, SkColorGetB(color)))
      .Check();
  color_array
      ->CreateDataProperty(context, 3,
                           v8::Int32::New(isolate, SkColorGetA(color)))
      .Check();

  return color_array;
}

bool ArrayToSkColor(v8::Isolate* isolate,
                    v8::Local<v8::Value> color,
                    SkColor* result) {
  if (!color->IsArray()) {
    return false;
  }

  std::vector<int> colors;
  if (!gin::ConvertFromV8(isolate, color, &colors)) {
    return false;
  } else if (colors.size() != 4) {
    return false;
  }

  for (const int& color : colors) {
    if ((color < 0) || (color > 255)) {
      return false;
    }
  }

  *result = SkColorSetARGB(colors[3], colors[0], colors[1], colors[2]);
  return true;
}

std::string SkColorToHexString(SkColor color) {
  return base::StringPrintf("#%02X%02X%02X", SkColorGetR(color),
                            SkColorGetG(color), SkColorGetB(color));
}

// Populates a Javascript NTP tile object for returning from rebel.ntpTiles.
// TODO: For security, tiles should be in an <iframe>.
v8::Local<v8::Object> GenerateNtpTile(
    v8::Isolate* isolate,
    RemoteNtp::RemoteNtpTileCache::ItemIDPair id_and_tile) {
  return gin::DataObjectBuilder(isolate)
      .Set("title", id_and_tile.second.title)
      .Set("url", id_and_tile.second.url)
      .Set("favicon_url", id_and_tile.second.favicon_url)
      .Build();
}

// Populates a Javascript autocomplete classification object for returning from
// rebel.search.autocompleteResult.matches.(contentsClass|descriptionClass).
v8::Local<v8::Object> GenerateMatchClassification(
    v8::Isolate* isolate,
    const std::vector<rebel::mojom::ACMatchClassificationPtr>&
        classifications) {
  v8::Local<v8::Object> v8_result =
      v8::Array::New(isolate, classifications.size());
  v8::Local<v8::Context> context = isolate->GetCurrentContext();

  for (size_t i = 0; i < classifications.size(); ++i) {
    v8::Local<v8::Object> v8_entry =
        gin::DataObjectBuilder(isolate)
            .Set("offset", classifications[i]->offset)
            .Set("style", classifications[i]->style)
            .Build();

    v8_result->CreateDataProperty(context, i, v8_entry).Check();
  }

  return v8_result;
}

// Populates a Javascript autocomplete result object for returning from
// rebel.search.autocompleteResult.
v8::Local<v8::Object> GenerateAutocompleteMatches(
    v8::Isolate* isolate,
    const std::vector<rebel::mojom::AutocompleteMatchPtr>& matches) {
  v8::Local<v8::Object> v8_matches = v8::Array::New(isolate, matches.size());
  v8::Local<v8::Context> context = isolate->GetCurrentContext();

  for (size_t i = 0; i < matches.size(); ++i) {
    const rebel::mojom::AutocompleteMatchPtr& match = matches[i];

    v8::Local<v8::Object> v8_match =
        gin::DataObjectBuilder(isolate)
            .Set("contents", match->contents)
            .Set("contentsClass",
                 GenerateMatchClassification(isolate, match->contents_class))
            .Set("description", match->description)
            .Set("descriptionClass",
                 GenerateMatchClassification(isolate, match->description_class))
            .Set("destinationUrl", match->destination_url)
            .Set("type", match->type)
            .Set("isSearchType", match->is_search_type)
            .Set("fillIntoEdit", match->fill_into_edit)
            .Set("inlineAutocompletion", match->inline_autocompletion)
            .Set("allowedToBeDefaultMatch", match->allowed_to_be_default_match)
            .Build();

    v8_matches->CreateDataProperty(context, i, v8_match).Check();
  }

  return v8_matches;
}

// Populates a Javascript background collection object for returning from
// rebel.theme.backgroundCollections.
v8::Local<v8::Object> GenerateBackgroundCollection(
    v8::Isolate* isolate,
    const rebel::mojom::BackgroundCollectionPtr& collection) {
  return gin::DataObjectBuilder(isolate)
      .Set("collectionId", collection->collection_id)
      .Set("collectionName", collection->collection_name)
      .Set("previewImageUrl", collection->preview_image_url.spec())
      .Build();
}

// Populates a Javascript background image object for returning from
// rebel.theme.backgroundImages.
v8::Local<v8::Object> GenerateBackgroundImage(
    v8::Isolate* isolate,
    const rebel::mojom::BackgroundImagePtr& image) {
  return gin::DataObjectBuilder(isolate)
      .Set("imageUrl", image->image_url.spec())
      .Set("thumbnailUrl", image->thumbnail_url.spec())
      .Set("attributionLine1", image->attribution_line_1)
      .Set("attributionLine2", image->attribution_line_2)
      .Set("attributionUrl", image->attribution_url.spec())
      .Build();
}

// Populates a Javascript theme object for returning from rebel.theme.theme.
v8::Local<v8::Object> GenerateTheme(
    v8::Isolate* isolate,
    const rebel::mojom::RemoteNtpThemePtr& theme) {
  v8::Local<v8::Object> background =
      gin::DataObjectBuilder(isolate)
          .Set("collectionId", theme->collection_id)
          .Set("imageUrl", theme->image_url.spec())
          .Set("imageAlignment", theme->image_alignment)
          .Set("imageTiling", theme->image_tiling)
          .Set("attributionLine1", theme->attribution_line_1)
          .Set("attributionLine2", theme->attribution_line_2)
          .Set("attributionUrl", theme->attribution_url.spec())
          .Set("attributionImageUrl", theme->attribution_image_url.spec())
          .Build();

  v8::Local<v8::Object> colors =
      gin::DataObjectBuilder(isolate)
          .Set("colorId", theme->color_id)
          .Set("color", SkColorToArray(isolate, theme->color))
          .Set("colorDark", SkColorToArray(isolate, theme->color_dark))
          .Set("colorLight", SkColorToArray(isolate, theme->color_light))
          .Build();

  return gin::DataObjectBuilder(isolate)
      .Set("darkModeEnabled", theme->dark_mode_enabled)
      .Set("background", background)
      .Set("colors", colors)
      .Build();
}

std::string GenerateDataUrlForColor(SkColor color) {
  static constexpr const char kColorsIconTemplate[] =
      "<svg xmlns=\"http://www.w3.org/2000/svg\" "
      "xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"64\" "
      "height=\"64\"><defs><path d=\"M32 64C14.34 64 0 49.66 0 32S14.34 0 32 "
      "0s32 14.34 32 32-14.34 32-32 32z\" id=\"a\"/><linearGradient id=\"b\" "
      "gradientUnits=\"userSpaceOnUse\" x1=\"32\" y1=\"32\" x2=\"32.08\" "
      "y2=\"32\"><stop offset=\"0\%\" stop-color=\"$2\"/><stop "
      "offset=\"100\%\" stop-color=\"$1\"/></linearGradient><clipPath "
      "id=\"c\"><use xlink:href=\"#a\"/></clipPath></defs><use "
      "xlink:href=\"#a\" fill=\"url(#b)\"/><g clip-path=\"url(#c)\"><use "
      "xlink:href=\"#a\" fill-opacity=\"0\" stroke=\"$1\" "
      "stroke-width=\"2\"/></g></svg>";

  AutogeneratedThemeColors colors = GetAutogeneratedThemeColors(color);

  std::vector<std::string> substitutions;
  substitutions.push_back(SkColorToHexString(colors.frame_color));
  substitutions.push_back(SkColorToHexString(colors.active_tab_color));

  std::string svg_base64;
  base::Base64Encode(
      base::ReplaceStringPlaceholders(kColorsIconTemplate, substitutions, NULL),
      &svg_base64);

  return "data:image/svg+xml;base64," + svg_base64;
}

bool IsUrlValid(const GURL& url) {
  return url.is_valid() && !blink::IsRendererDebugURL(url);
}

content::RenderFrame* GetMainRenderFrameForCurrentContext() {
  blink::WebLocalFrame* frame = blink::WebLocalFrame::FrameForCurrentContext();
  if (!frame) {
    return nullptr;
  }

  content::RenderFrame* main_frame =
      content::RenderFrame::FromWebFrame(frame->LocalRoot());
  if (!main_frame || !main_frame->IsMainFrame()) {
    return nullptr;
  }

  return main_frame;
}

RemoteNtp* GetRemoteNtpForCurrentContext() {
  content::RenderFrame* main_frame = GetMainRenderFrameForCurrentContext();
  if (!main_frame) {
    return nullptr;
  }

  return RemoteNtp::Get(main_frame);
}

// Javascript to C++ bindings for window.rebel.
class RemoteNtpBindings : public gin::Wrappable<RemoteNtpBindings> {
 public:
  static gin::WrapperInfo kWrapperInfo;

  RemoteNtpBindings() {}
  ~RemoteNtpBindings() override {}

 private:
  RemoteNtpBindings(const RemoteNtpBindings&) = delete;
  RemoteNtpBindings& operator=(const RemoteNtpBindings&) = delete;

  gin::ObjectTemplateBuilder GetObjectTemplateBuilder(
      v8::Isolate* isolate) final {
    return gin::Wrappable<RemoteNtpBindings>::GetObjectTemplateBuilder(isolate)
        .SetProperty("ntpTilesAvailable",
                     &RemoteNtpBindings::AreNtpTilesAvailable)
        .SetProperty("ntpTiles", &RemoteNtpBindings::GetNtpTiles)
        .SetProperty("platformInfo", &RemoteNtpBindings::GetPlatformInfo)
        .SetMethod("addCustomTile", &RemoteNtpBindings::AddCustomTile)
        .SetMethod("removeCustomTile", &RemoteNtpBindings::RemoveCustomTile)
        .SetMethod("editCustomTile", &RemoteNtpBindings::EditCustomTile)
        .SetMethod("loadInternalUrl", &RemoteNtpBindings::LoadInternalUrl);
  }

  static bool AreNtpTilesAvailable() {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return false;
    }

    return remote_ntp->AreNtpTilesAvailable();
  }

  static v8::Local<v8::Value> GetNtpTiles(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

    RemoteNtp::RemoteNtpTileCache::ItemIDVector tiles;
    remote_ntp->GetNtpTiles(&tiles);

    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Local<v8::Object> v8_tiles = v8::Array::New(isolate, tiles.size());

    for (size_t i = 0; i < tiles.size(); ++i) {
      v8::Local<v8::Object> tile = GenerateNtpTile(isolate, tiles[i]);
      v8_tiles->CreateDataProperty(context, i, tile).Check();
    }

    return v8_tiles;
  }

  static v8::Local<v8::Value> GetPlatformInfo(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

    const std::string platform = version_info::GetOSType();
    const std::string version = version_info::GetVersionNumber();

    // This is how chrome://version determines browser architecture.
    int browser_arch = (sizeof(void*) == 8) ? 64 : 32;

    const std::string arch_name = base::SysInfo::OperatingSystemArchitecture();
    int system_arch = -1;

    if (!arch_name.empty()) {
      system_arch = arch_name.find("64") != std::string::npos ? 64 : 32;
    }

    return gin::DataObjectBuilder(isolate)
        .Set("platform", platform)
        .Set("version", version)
        .Set("browserArch", browser_arch)
        .Set("systemArch", system_arch)
        .Build();
  }

  static void AddCustomTile(const std::string& tile_url,
                            const std::u16string& tile_title) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    const GURL validated_url(tile_url);

    if (!IsUrlValid(validated_url) || tile_title.empty()) {
      return;
    }

    remote_ntp->AddCustomTile(validated_url, tile_title);
  }

  static void RemoveCustomTile(const std::string& tile_url) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    const GURL validated_url(tile_url);

    if (!IsUrlValid(validated_url)) {
      return;
    }

    remote_ntp->RemoveCustomTile(validated_url);
  }

  static void EditCustomTile(const std::string& old_tile_url,
                             const std::string& new_tile_url,
                             const std::u16string& new_tile_title) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    const GURL old_validated_url(old_tile_url);
    const GURL new_validated_url(new_tile_url);

    if ((new_tile_url.empty() && new_tile_title.empty()) ||
        !IsUrlValid(old_validated_url) ||
        (!new_tile_url.empty() && !IsUrlValid(new_validated_url))) {
      return;
    }

    remote_ntp->EditCustomTile(old_validated_url, new_validated_url,
                               new_tile_title);
  }

  static void LoadInternalUrl(const std::string& url) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    const GURL validated_url(url);

    // Only allow chrome:// URLs that won't crash the browser. We could return
    // a boolean, but let's not let third-party websites probe for "safe" URLs.
    if (!IsUrlValid(validated_url) ||
        !validated_url.SchemeIs(content::kChromeUIScheme)) {
      return;
    }

    remote_ntp->LoadInternalUrl(validated_url);
  }
};

// Javascript to C++ bindings for window.rebel.search.
class SearchBindings : public gin::Wrappable<SearchBindings> {
 public:
  static gin::WrapperInfo kWrapperInfo;

  SearchBindings() {}
  ~SearchBindings() override {}

 private:
  SearchBindings(const SearchBindings&) = delete;
  SearchBindings& operator=(const SearchBindings&) = delete;

  gin::ObjectTemplateBuilder GetObjectTemplateBuilder(
      v8::Isolate* isolate) final {
    return gin::Wrappable<SearchBindings>::GetObjectTemplateBuilder(isolate)
        .SetProperty("autocompleteResult",
                     &SearchBindings::GetAutocompleteResult)
        .SetMethod("queryAutocomplete", &SearchBindings::QueryAutocomplete)
        .SetMethod("stopAutocomplete", &SearchBindings::StopAutocomplete)
        .SetMethod("openAutocompleteMatch",
                   &SearchBindings::OpenAutocompleteMatch);
  }

  static v8::Local<v8::Value> GetAutocompleteResult(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

    const rebel::mojom::AutocompleteResultPtr& result =
        remote_ntp->GetAutocompleteResult();
    if (!result) {
      return v8::Null(isolate);
    }

    return gin::DataObjectBuilder(isolate)
        .Set("input", result->input)
        .Set("matches", GenerateAutocompleteMatches(isolate, result->matches))
        .Build();
  }

  static void QueryAutocomplete(const std::u16string& input,
                                bool prevent_inline_autocomplete) {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->QueryAutocomplete(input, prevent_inline_autocomplete);
  }

  static void StopAutocomplete() {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->StopAutocomplete();
  }

  static void OpenAutocompleteMatch(uint32_t index,
                                    const std::string& url,
                                    bool middle_button,
                                    bool alt_key,
                                    bool ctrl_key,
                                    bool meta_key,
                                    bool shift_key) {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->OpenAutocompleteMatch(index, GURL(url), middle_button, alt_key,
                                      ctrl_key, meta_key, shift_key);
  }
};

// Javascript to C++ bindings for window.rebel.theme.
class ThemeBindings : public gin::Wrappable<ThemeBindings> {
 public:
  static gin::WrapperInfo kWrapperInfo;

  ThemeBindings() {}
  ~ThemeBindings() override {}

 private:
  ThemeBindings(const ThemeBindings&) = delete;
  ThemeBindings& operator=(const ThemeBindings&) = delete;

  gin::ObjectTemplateBuilder GetObjectTemplateBuilder(
      v8::Isolate* isolate) final {
    return gin::Wrappable<ThemeBindings>::GetObjectTemplateBuilder(isolate)
        .SetProperty("backgroundCollections",
                     &ThemeBindings::GetBackgroundCollections)
        .SetProperty("backgroundImages", &ThemeBindings::GetBackgroundImages)
        .SetProperty("theme", &ThemeBindings::GetTheme)
        .SetProperty("colors", &ThemeBindings::GetThemeColors)
        .SetMethod("loadBackgroundCollections",
                   &ThemeBindings::LoadBackgroundCollections)
        .SetMethod("loadBackgroundImages", &ThemeBindings::LoadBackgroundImages)
        .SetMethod("setBackgroundImage", &ThemeBindings::SetBackgroundImage)
        .SetMethod("selectLocalBackgroundImage",
                   &ThemeBindings::SelectLocalBackgroundImage)
        .SetMethod("previewColor", &ThemeBindings::PreviewColor)
        .SetMethod("revertColor", &ThemeBindings::RevertColor)
        .SetMethod("commitColor", &ThemeBindings::CommitColor);
  }

  static v8::Local<v8::Value> GetBackgroundCollections(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

    const rebel::RemoteNtpBackgroundCollectionList& collections =
        remote_ntp->GetBackgroundCollections();

    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Local<v8::Object> v8_collections =
        v8::Array::New(isolate, collections.size());

    for (size_t i = 0; i < collections.size(); ++i) {
      const auto& collection = collections[i];

      auto v8_collection = GenerateBackgroundCollection(isolate, collection);
      v8_collections->CreateDataProperty(context, i, v8_collection).Check();
    }

    return v8_collections;
  }

  static v8::Local<v8::Value> GetBackgroundImages(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

    const rebel::RemoteNtpBackgroundImageMap& images =
        remote_ntp->GetBackgroundImages();

    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    gin::DataObjectBuilder v8_images(isolate);

    for (auto it = images.begin(); it != images.end(); ++it) {
      v8::Local<v8::Object> v8_collection =
          v8::Array::New(isolate, it->second.size());

      for (size_t i = 0; i < it->second.size(); ++i) {
        const auto& image = it->second[i];

        auto v8_image = GenerateBackgroundImage(isolate, image);
        v8_collection->CreateDataProperty(context, i, v8_image).Check();
      }

      v8_images.Set(it->first, v8_collection);
    }

    return v8_images.Build();
  }

  static v8::Local<v8::Value> GetTheme(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

    const rebel::mojom::RemoteNtpThemePtr& theme = remote_ntp->GetTheme();
    if (!theme) {
      return v8::Null(isolate);
    }

    return GenerateTheme(isolate, theme);
  }

  static v8::Local<v8::Value> GetThemeColors(v8::Isolate* isolate) {
    const RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return v8::Null(isolate);
    }

#if defined(OS_ANDROID)
    return v8::Array::New(isolate, 0);
#else
    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Local<v8::Object> v8_colors =
        v8::Array::New(isolate, chrome_colors::kNumColorsInfo);

    for (size_t i = 0; i < chrome_colors::kNumColorsInfo; ++i) {
      const chrome_colors::ColorInfo& color_info =
          chrome_colors::kGeneratedColorsInfo[i];

      v8::Local<v8::Object> v8_color_info =
          gin::DataObjectBuilder(isolate)
              .Set("colorId", color_info.id)
              .Set("color", SkColorToArray(isolate, color_info.color))
              .Set("label", l10n_util::GetStringUTF16(color_info.label_id))
              .Set("icon", GenerateDataUrlForColor(color_info.color))
              .Build();

      v8_colors->CreateDataProperty(context, i, v8_color_info).Check();
    }

    return v8_colors;
#endif
  }

  static void LoadBackgroundCollections() {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->LoadBackgroundCollections();
  }

  static void LoadBackgroundImages(const std::string& collection_id) {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    if (collection_id.empty()) {
      return;
    }

    remote_ntp->LoadBackgroundImages(collection_id);
  }

  static void SetBackgroundImage(const std::string& collection_id,
                                 const std::string& image_url,
                                 const std::string& attribution_line_1,
                                 const std::string& attribution_line_2,
                                 const std::string& attribution_url) {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    // Reset back to default.
    if (collection_id.empty()) {
      remote_ntp->SetBackgroundImage(collection_id, nullptr);
      return;
    }

    GURL validated_image_url(image_url);
    GURL validated_attribution_url(attribution_url);

    // The attribution URL may be empty, but the image URL must be set.
    if (!IsUrlValid(validated_image_url) ||
        (!attribution_url.empty() && !IsUrlValid(validated_attribution_url))) {
      return;
    }

    auto image = rebel::mojom::BackgroundImage::New(
        validated_image_url, GURL() /* thumbnail not needed */,
        attribution_line_1, attribution_line_2, validated_attribution_url);

    remote_ntp->SetBackgroundImage(collection_id, std::move(image));
  }

  static void SelectLocalBackgroundImage() {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->SelectLocalBackgroundImage();
  }

  static void PreviewColor(v8::Isolate* isolate, v8::Local<v8::Value> value) {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    SkColor color;

    if (!ArrayToSkColor(isolate, value, &color)) {
      return;
    }

    remote_ntp->PreviewColor(color);
  }

  static void RevertColor() {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->RevertColor();
  }

  static void CommitColor() {
    RemoteNtp* remote_ntp = GetRemoteNtpForCurrentContext();
    if (!remote_ntp) {
      return;
    }

    remote_ntp->CommitColor();
  }
};

gin::WrapperInfo RemoteNtpBindings::kWrapperInfo = {gin::kEmbedderNativeGin};
gin::WrapperInfo SearchBindings::kWrapperInfo = {gin::kEmbedderNativeGin};
gin::WrapperInfo ThemeBindings::kWrapperInfo = {gin::kEmbedderNativeGin};

}  // namespace

// static
void RemoteNtpExtension::Install(blink::WebLocalFrame* frame) {
  v8::Isolate* isolate = blink::MainThreadIsolate();
  v8::HandleScope handle_scope(isolate);
  v8::Local<v8::Context> context = frame->MainWorldScriptContext();
  if (context.IsEmpty()) {
    return;
  }

  v8::Context::Scope context_scope(context);

  gin::Handle<RemoteNtpBindings> remote_ntp_controller =
      gin::CreateHandle(isolate, new RemoteNtpBindings());
  if (remote_ntp_controller.IsEmpty()) {
    return;
  }

  gin::Handle<SearchBindings> search_controller =
      gin::CreateHandle(isolate, new SearchBindings());
  if (search_controller.IsEmpty()) {
    return;
  }

  gin::Handle<ThemeBindings> theme_controller =
      gin::CreateHandle(isolate, new ThemeBindings());
  if (theme_controller.IsEmpty()) {
    return;
  }

  v8::Local<v8::Object> remote_ntp =
      remote_ntp_controller.ToV8()->ToObject(context).ToLocalChecked();
  remote_ntp
      ->Set(context, gin::StringToV8(isolate, "search"),
            search_controller.ToV8())
      .ToChecked();
  remote_ntp
      ->Set(context, gin::StringToV8(isolate, "theme"), theme_controller.ToV8())
      .ToChecked();

  v8::Local<v8::Object> global = context->Global();
  global->Set(context, gin::StringToV8(isolate, "rebel"), remote_ntp)
      .ToChecked();
}

// static
void RemoteNtpExtension::DispatchNtpTilesChanged(blink::WebLocalFrame* frame) {
  Dispatch(frame, kDispatchNtpTilesChangedScript);
}

// static
void RemoteNtpExtension::DispatchAutocompleteResultChanged(
    blink::WebLocalFrame* frame) {
  Dispatch(frame, kDispatchAutocompleteResultChanged);
}

// static
void RemoteNtpExtension::DispatchBackgroundCollectionsChanged(
    blink::WebLocalFrame* frame) {
  Dispatch(frame, kDispatchBackgroundCollectionsChangedScript);
}

// static
void RemoteNtpExtension::DispatchBackgroundImagesChanged(
    blink::WebLocalFrame* frame) {
  Dispatch(frame, kDispatchBackgroundImagesChangedScript);
}

// static
void RemoteNtpExtension::DispatchLocalBackgroundImageSelected(
    blink::WebLocalFrame* frame) {
  Dispatch(frame, kDispatchLocalBackgroundImageSelectedScript);
}

// static
void RemoteNtpExtension::DispatchThemeChanged(blink::WebLocalFrame* frame) {
  Dispatch(frame, kDispatchThemeChangedScript);
}

}  // namespace rebel
